<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFrameworks>netstandard2.0</TargetFrameworks>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<IsRoslynComponent>true</IsRoslynComponent>
		<GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
		<NoWarn>CS1570;CS1587</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\.editorconfig" Link=".editorconfig" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.Common">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.ResxSourceGenerator">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Newtonsoft.Json">
			<GeneratePathProperty>true</GeneratePathProperty>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Templates.resx" EmitFormatMethods="true" Public="false" />
	</ItemGroup>
	
	<ItemGroup>
		<!-- Package the generator in the analyzer directory of the nuget package -->
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>

	<Target Name="GetDependencyTargetPaths">
		<ItemGroup>
			<!-- 优先使用 NuGet 生成的 Pkg 属性（需要已还原） -->
			<TargetPathWithTargetPlatformMoniker
				Include="$(PkgNewtonsoft_Json)\lib\netstandard2.0\Newtonsoft.Json.dll"
				IncludeRuntimeDependency="false"
				Condition=" '$(PkgNewtonsoft_Json)' != '' " />

			<!-- 回退到 NuGet 全局包缓存（当未生成 Pkg 属性时） -->
			<TargetPathWithTargetPlatformMoniker
				Include="$(NuGetPackageRoot)newtonsoft.json\13.0.4\lib\netstandard2.0\Newtonsoft.Json.dll"
				IncludeRuntimeDependency="false"
				Condition=" '$(PkgNewtonsoft_Json)' == '' " />
		</ItemGroup>
	</Target>

</Project>
