//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XinjingdailyBot.Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Emojis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Emojis() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XinjingdailyBot.Infrastructure.Localization.Emojis", typeof(Emojis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ↩️ 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🔷 的本地化字符串。
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 👻 的本地化字符串。
        /// </summary>
        public static string Ghost {
            get {
                return ResourceManager.GetString("Ghost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🐴 的本地化字符串。
        /// </summary>
        public static string Horse {
            get {
                return ResourceManager.GetString("Horse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ❌ 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🔶 的本地化字符串。
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🏳️‍⚧️|🇺🇦|🇹🇼|🍥 的本地化字符串。
        /// </summary>
        public static string PureStrings {
            get {
                return ResourceManager.GetString("PureStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🖼️ 的本地化字符串。
        /// </summary>
        public static string SpoilerOff {
            get {
                return ResourceManager.GetString("SpoilerOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️ 的本地化字符串。
        /// </summary>
        public static string SpoilerOn {
            get {
                return ResourceManager.GetString("SpoilerOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🤔 的本地化字符串。
        /// </summary>
        public static string Thinking {
            get {
                return ResourceManager.GetString("Thinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️ 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ✅ 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
