//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XinjingdailyBot.Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XinjingdailyBot.Infrastructure.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 您已被{0}封禁, 理由: {1}, 您将无法继续使用投稿功能和大部分命令 的本地化字符串。
        /// </summary>
        public static string BanedUserTips {
            get {
                return ResourceManager.GetString("BanedUserTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有权限 的本地化字符串。
        /// </summary>
        public static string NoPostRight {
            get {
                return ResourceManager.GetString("NoPostRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投稿已取消 的本地化字符串。
        /// </summary>
        public static string PostCanceled {
            get {
                return ResourceManager.GetString("PostCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稿件已成功投递 的本地化字符串。
        /// </summary>
        public static string PostSendSuccess {
            get {
                return ResourceManager.GetString("PostSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 封禁记录自助查询: /myban 如果对封禁记录有异议, 请联系频道管理员 的本地化字符串。
        /// </summary>
        public static string QueryBanDescribe {
            get {
                return ResourceManager.GetString("QueryBanDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未设置审核群组, 无法接收投稿 的本地化字符串。
        /// </summary>
        public static string ReviewGroupNotSet {
            get {
                return ResourceManager.GetString("ReviewGroupNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本为空, 无法创建投稿 的本地化字符串。
        /// </summary>
        public static string TextPostCantBeNull {
            get {
                return ResourceManager.GetString("TextPostCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 感谢您的投稿, 审核结果将会稍后通知 的本地化字符串。
        /// </summary>
        public static string ThanksForSendingPost {
            get {
                return ResourceManager.GetString("ThanksForSendingPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已被{0}解封, 理由: {1}, 已恢复您的投稿和命令权限 的本地化字符串。
        /// </summary>
        public static string UnbanedUserTips {
            get {
                return ResourceManager.GetString("UnbanedUserTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您受到了一次警告, 理由: {0} 的本地化字符串。
        /// </summary>
        public static string WarnUserTips {
            get {
                return ResourceManager.GetString("WarnUserTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前累计受到警告&lt;code&gt;{0}&lt;/code&gt;次, 达到&lt;code&gt;{1}&lt;/code&gt;次后将会被系统自动封禁 的本地化字符串。
        /// </summary>
        public static string WarnUserTips2 {
            get {
                return ResourceManager.GetString("WarnUserTips2", resourceCulture);
            }
        }
    }
}
