FROM debian:12-slim

WORKDIR /app
COPY appsettings.template.json /app
COPY entrypoint.sh /app

RUN apt-get update && \
    apt-get install -y cron wget unzip && \
    apt-get install -y libicu72 curl && \
    wget https://github.com/chr233/XinjingdailyBot/releases/download/2.2.4.1/linux-x64-fde.zip && \
    unzip linux-x64-fde.zip && chmod +x ./XinjingdailyBot.WebAPI && rm -f ./linux-x64-fde.zip &&  \
    chmod +x ./entrypoint.sh && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get purge -y --auto-remove wget unzip

ENTRYPOINT [ "./entrypoint.sh" ]