<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ConfigureAwaitChecker.Analyzer" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\XinjingDaily.Bot.Infrastructure\XinjingDaily.Bot.Infrastructure.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.Interface\XinjingDaily.Bot.Interface.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.Repository\XinjingDaily.Bot.Repository.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\.editorconfig" Link=".editorconfig" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="NLog" />
		<PackageReference Include="NRedisStack" />
		<PackageReference Include="Quartz" />
		<PackageReference Include="Telegram.Bot" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Quartz" />
	</ItemGroup>

</Project>
