<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="NLog.Extensions.Logging" />
		<PackageReference Include="Quartz.AspNetCore" />
		<PackageReference Include="Spectre.Console" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
		<PackageReference Include="ConfigureAwaitChecker.Analyzer" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\XinjingDaily.Bot.Command\XinjingDaily.Bot.Command.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.Controllers\XinjingDaily.Bot.Controllers.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.Infrastructure\XinjingDaily.Bot.Infrastructure.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.Interface\XinjingDaily.Bot.Interface.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.Repository\XinjingDaily.Bot.Repository.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.Service\XinjingDaily.Bot.Service.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.Tasks\XinjingDaily.Bot.Tasks.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\.editorconfig" Link=".editorconfig" />
	</ItemGroup>

</Project>
