<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SqlSugarCore" />
		<PackageReference Include="ConfigureAwaitChecker.Analyzer" PrivateAssets="all" />
		<PackageReference Include="StackExchange.Redis" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\.editorconfig" Link=".editorconfig" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\XinjingDaily.Bot.Generator\XinjingDaily.Bot.Generator.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" ReferPrivateAssets="all" />
		<ProjectReference Include="..\XinjingDaily.Bot.Infrastructure\XinjingDaily.Bot.Infrastructure.csproj" />
	</ItemGroup>

</Project>
