using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace XinjingDaily.Bot.Generator.Generators;

[Generator]
public class SugarTableIncrementalGenerator : IIncrementalGenerator
{
    // SqlSugar 特性完整名称
    private const string SugarTableAttributeFullName = "SqlSugar.SugarTable";

    /// <summary>
    /// 语法过滤：快速判断是否是【带特性的类】
    /// </summary>
    private static bool IsCandidateClass(SyntaxNode node)
    {
        // 支持 class 和 record，且包含 attribute 列表才处理
        if (node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0)
        {
            return true;
        }
        if (node is RecordDeclarationSyntax rds && rds.AttributeLists.Count > 0)
        {
            return true;
        }
        return false;
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1 获取符号
        var sugarTableSymbol = context.CompilationProvider
            .Select(static (compilation, _) =>
                compilation.GetTypeByMetadataName(SugarTableAttributeFullName));

        // 2 筛选所有带特性的类
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateClass(node),
                transform: static (ctx, _) => Utils.GetClassOrRecordSymbol(ctx))
            .Where(symbol => symbol is not null);

        // 3 过滤出带 [SugarTable] 的类
        var entryClassList = classDeclarations
            .Combine(sugarTableSymbol)
            .Where(static pair => Utils.HasTargetAttribute(pair.Left, pair.Right))
            .Select(static (pair, _) => pair.Left)
            .Collect();

        // 4 将类列表与 Compilation 合并，回调中就能拿到 compilation
        var classesAndCompilation = entryClassList.Combine(context.CompilationProvider);

        // 5 组合并生成代码
        context.RegisterSourceOutput(classesAndCompilation, Execute);
    }

    /// <summary>
    /// 生成最终代码
    /// </summary>
    private void Execute(SourceProductionContext context, (ImmutableArray<INamedTypeSymbol?> Left, Compilation Right) pair)
    {
        var entryClasses = pair.Left;
        var compilation = pair.Right;

        if (entryClasses.IsEmpty)
        {
            var warn = Diagnostic.Create(DiagnosticUtils.EntryNotFoundDiagnostic, null);
            context.ReportDiagnostic(warn);

            return;
        }

        var assemblyName = (compilation.AssemblyName ?? "UnknownProject").Replace(".", "");

        var code = new StringBuilder();
        code.AppendLine("// Generated by SugarTableIncrementalGenerator");
        code.AppendLine("using SqlSugar;");
        code.AppendLine("using Microsoft.Extensions.Logging;");
        code.AppendLine();
        code.AppendLine("namespace XinjingDaily.Bot.Generator;");
        code.AppendLine();
        code.AppendLine($"public static class {assemblyName}Extension");
        code.AppendLine("{");
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 根据类型创建实体表");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    private static void SafeCreateTable<T>(ISqlSugarClient db, ILogger logger)");
        code.AppendLine("    {");
        code.AppendLine("       try");
        code.AppendLine("       {");
        code.AppendLine("           db.CodeFirst.InitTables<T>();");
        code.AppendLine("           logger.LogDebug(\"创建表 {type} 成功\");");
        code.AppendLine("       }");
        code.AppendLine("       catch (Exception ex)");
        code.AppendLine("       {");
        code.AppendLine("           logger.LogWarning(ex, \"创建表 {type} 失败, 可能没有权限\", typeof(T).Name);");
        code.AppendLine("       }");
        code.AppendLine("    }");
        code.AppendLine();
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 自动创建所有 [SugarTable] 实体表");
        code.AppendLine("    /// </summary>");
        code.AppendLine($"    public static void Create{assemblyName}Tables(this ISqlSugarClient db, ILogger logger)");
        code.AppendLine("    {");

        // 生成 SafeCreateTable 代码
        foreach (var type in entryClasses)
        {
            if (type == null)
            {
                continue;
            }
            var fullName = type.ToDisplayString(); // 完整命名空间+类名
            code.AppendLine($"        SafeCreateTable<{fullName}>(db, logger);");
        }

        code.AppendLine("    }");
        code.AppendLine("}");

        var sourceFileName = $"{assemblyName}.{nameof(SugarTableIncrementalGenerator)}.g.cs";

        // 添加到编译
        context.AddSource(sourceFileName, SourceText.From(code.ToString(), Encoding.UTF8));
    }
}