<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ConfigureAwaitChecker.Analyzer" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Microsoft.CodeAnalysis.ResxSourceGenerator" PrivateAssets="all" />
		<PackageReference Include="NLog" />
		<PackageReference Include="Telegram.Bot" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\.editorconfig" Link=".editorconfig" />
	</ItemGroup>
	
	<ItemGroup>
		<EmbeddedResource Update="Localization\Langs.resx" EmitFormatMethods="true" Public="true" />
		<EmbeddedResource Update="Localization\Emojis.resx" EmitFormatMethods="true" Public="true" />
	</ItemGroup>

</Project>