<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
		<UserSecretsId>f13b8c22-3acd-4166-bded-768afc427f3b</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<AdditionalFiles Include="Properties\appService.json" />
		<AdditionalFiles Include="Properties\dbtable.json" />
		<AdditionalFiles Include="Properties\launchSettings.json" />
		<AdditionalFiles Include="Properties\schedule.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="NLog.Extensions.Logging" />
		<PackageReference Include="NSwag.AspNetCore" />
		<PackageReference Include="NSwag.Generation.AspNetCore" />
		<PackageReference Include="Quartz.AspNetCore" />
		<PackageReference Include="SqlSugarCore" />
		<PackageReference Include="ConfigureAwaitChecker.Analyzer" PrivateAssets="all" />
		<PackageReference Include="Telegram.Bot" />
		<PackageReference Include="Scalar.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\XinjingdailyBot.Command\XinjingdailyBot.Command.csproj" />
		<ProjectReference Include="..\XinjingdailyBot.Controller\XinjingdailyBot.Controller.csproj" />
		<ProjectReference Include="..\XinjingdailyBot.Infrastructure\XinjingdailyBot.Infrastructure.csproj" />
		<ProjectReference Include="..\XinjingdailyBot.Interface\XinjingdailyBot.Interface.csproj" />
		<ProjectReference Include="..\XinjingdailyBot.Model\XinjingdailyBot.Model.csproj" />
		<ProjectReference Include="..\XinjingdailyBot.Repository\XinjingdailyBot.Repository.csproj" />
		<ProjectReference Include="..\XinjingdailyBot.Service\XinjingdailyBot.Service.csproj" />
		<ProjectReference Include="..\XinjingdailyBot.Tasks\XinjingdailyBot.Tasks.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\.editorconfig" Link=".editorconfig" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='Debug'">

	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='Release'">
		<ProjectReference Include="..\XinjingdailyBot.Generator\XinjingdailyBot.Generator.csproj">
			<OutputItemType>Analyzer</OutputItemType>
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<Content Include="..\LICENSE.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Content Include="..\README.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Content Update="config\nlog.config">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>