<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="LocalLow\**" />
	  <Compile Remove="Services\**" />
	  <EmbeddedResource Remove="LocalLow\**" />
	  <EmbeddedResource Remove="Services\**" />
	  <None Remove="LocalLow\**" />
	  <None Remove="Services\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ConfigureAwaitChecker.Analyzer" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\XinjingDaily.Bot.Entry\XinjingDaily.Bot.Entry.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.Infrastructure\XinjingDaily.Bot.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\.editorconfig" Link=".editorconfig" />
	</ItemGroup>

</Project>
