<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<UserSecretsId>c798909b-7fb5-44be-83ad-3a0355d63f49</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="Properties\appService.json" />
		<Content Remove="Properties\dbtable.json" />
		<Content Remove="Properties\schedule.json" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Properties\launchSettings.json" />
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="Properties\appService.json" />
		<AdditionalFiles Include="Properties\dbtable.json" />
		<AdditionalFiles Include="Properties\launchSettings.json" />
		<AdditionalFiles Include="Properties\schedule.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="NLog.Extensions.Logging" />
		<PackageReference Include="NLog.Web.AspNetCore" />
		<PackageReference Include="NSwag.AspNetCore" />
		<PackageReference Include="Quartz.AspNetCore" />
		<PackageReference Include="Scalar.AspNetCore" />
		<PackageReference Include="SqlSugarCore" />
		<PackageReference Include="ConfigureAwaitChecker.Analyzer" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\XinjingDaily.Bot.Command\XinjingDaily.Bot.Command.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.Controllers\XinjingDaily.Bot.Controllers.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.Entry\XinjingDaily.Bot.Entry.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.Infrastructure\XinjingDaily.Bot.Infrastructure.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.Interface\XinjingDaily.Bot.Interface.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.Repository\XinjingDaily.Bot.Repository.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.Service\XinjingDaily.Bot.Service.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.SignalR\XinjingDaily.Bot.SignalR.csproj" />
		<ProjectReference Include="..\XinjingDaily.Bot.Tasks\XinjingDaily.Bot.Tasks.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='Debug'">

	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='Release'">
		<ProjectReference Include="..\XinjingDaily.Bot.Generator\XinjingDaily.Bot.Generator.csproj">
			<OutputItemType>Analyzer</OutputItemType>
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<None Include="..\.editorconfig" Link=".editorconfig" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="..\LICENSE.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Content Include="..\README.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
		</Content>
	</ItemGroup>


</Project>